version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=xsi
      - MONGO_INITDB_ROOT_PASSWORD=xsi
    volumes:
      - ./mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=xsi
      - ME_CONFIG_MONGODB_ADMINPASSWORD=xsi
      - ME_CONFIG_BASICAUTH_USERNAME=xsi
      - ME_CONFIG_BASICAUTH_PASSWORD=xsi
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb